### ISSUE TITLE
Documentation won't build with Sphinx

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/areaDetector#71]
I am trying to build the areaDetector documentation, and it is failing with this error:

```
Creating initial symlink: /home/epics/devel/areaDetector-3-9/docs/source/detectors.rst
Creating initial symlink: /home/epics/devel/areaDetector-3-9/docs/source/detector_drivers.rst
Creating initial symlink: /home/epics/devel/areaDetector-3-9/docs/source/install_guide.rst
Running Sphinx v3.1.2

Exception occurred:
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 1084, in add_source_parser
    self.registry.add_source_parser(*args, **kwargs)
TypeError: add_source_parser() takes 2 positional arguments but 3 were given
The full traceback has been saved in /tmp/sphinx-err-3vu6nb12.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [sphinx] Error 2
```

I did a "conda update sphinx" to see if that would fix the problem, but it did not.

This seems to be this Sphinx issue, but that issue is closed and I don't understand how to fix it.

https://github.com/sphinx-doc/sphinx/issues/7420

**Comment by prjemian** [comment]
Can you post the full `/tmp/sphinx-err-3vu6nb12.log` here?

**Comment by prjemian** [comment]
I'm thinking this comment (https://github.com/sphinx-doc/sphinx/issues/7420#issuecomment-609814898) may give us something to review.

**Comment by MarkRivers** [comment]
This is the full sphinx log of the last time I tried.  It does not have much more information that what I posted above.
```
corvette:~/devel/areaDetector/docs>more /tmp/sphinx-err-2t7ewejg.log
# Sphinx version: 3.1.2
# Python version: 3.7.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/registry.py", line 419, in load_extension
    metadata = setup(app)
  File "/home/epics/anaconda3/lib/python3.7/site-packages/m2r.py", line 652, in setup
    app.add_source_parser('.md', M2RParser)
  File "/home/epics/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 1084, in add_source_parser
    self.registry.add_source_parser(*args, **kwargs)
TypeError: add_source_parser() takes 2 positional arguments but 3 were given
```

**Comment by MarkRivers** [comment]
I solved this by creating a new conda environment with working versions of the required packages for sphinx.

The travis build was still working fine, so I created a conda environment using areaDetector/requirements.txt and the commands in .travis.yml:

```
conda create --name sphinx python=3.6
conda activate sphinx
pip install -r requirements.txt
pip install git+git://github.com/michaeljones/breathe.git@v4.11.1
pip install git+git://github.com/return42/linuxdoc.git
```

The only non-obvious thing which prevented me from figuring this out myself without the .travis.yml file was that just installing `breathe` without specifying the 4.11.1 version uninstalls sphinx 1.8.5 and installs 3.1.2, which does not work.

Now running make in docs succeeds:
```
make
...
Creating initial symlink: /home/epics/devel/areaDetector-3-9/docs/source/detectors.rst
Creating initial symlink: /home/epics/devel/areaDetector-3-9/docs/source/detector_drivers.rst
Creating initial symlink: /home/epics/devel/areaDetector-3-9/docs/source/install_guide.rst
2
Running Sphinx v1.8.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 105 source files that are out of date
updating environment: 105 added, 0 changed, 0 removed
/home/epics/anaconda3/envs/sphinx/lib/python3.6/site-packages/sphinx/util/nodes.py:94: FutureWarning:
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
reading sources... [100%] user_guide
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
/home/epics/anaconda3/envs/sphinx/lib/python3.6/site-packages/sphinx/writers/html.py:462: FutureWarning:
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  target_node = image_nodes and image_nodes[0] or node.parent
writing output... [100%] user_guide
generating indices... genindex
writing additional pages... search
copying images... [100%] pvaDriver/ADPvaDriver.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
```
